vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set nu")
vim.cmd("set relativenumber")
vim.cmd("set noshowmode")
vim.cmd("set clipboard=unnamedplus")

vim.g.mapleader = " "
vim.g.maplocalleader = " "
local map = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
map("n", "<Leader>w", ":w<CR>", opts)
map("n", "<Leader>q", ":wq<CR>", opts)
map("n", "<Leader>Q", ":q!<CR>", opts)
map("i", "kk", "<Esc>", opts)
map("v", "v", "<Esc>", opts)
map("n", "H", "<Esc>", opts)
map("n", "H", "^", opts)
map("n", "L", "$", opts)
map("n", "<Leader>w", ":w<CR>", opts)
map("n", "<Leader>q", ":wq<CR>", opts)
map("n", "<Leader>Q", ":q!<CR>", opts)
map("n", "U", "<C-r>", opts)
map("n", "<Leader>d", " <C-d>", opts)
map("n", "<Leader>u", " <C-u>", opts)
map("n", "<Leader>nhl", ":nohlsearch<CR>", opts)
map("n", "<Leader>v", "ggvG", opts)
map("n", "<Leader>rl", ":source $MYVIMRC<CR>", opts)
map("n", "sl", ":vsplit<CR><C-w>l", opts)
map("n", "sh", ":vsplit<CR><C-w>h", opts)
map("n", "sj", ":split<CR><C-w>j", opts)
map("n", "sk", ":split<CR><C-w>k", opts)
map("n", "<leader>t", ":term<CR>", opts)
map("n", "<leader>]", ":bn<CR>", opts)
map("n", "<leader>[", ":bp<CR>", opts)
